feat: defined a single APIConfig type in the root module and referenced it from individual SDKs
redhat-developer/app-services-sdk-go pull request #262
Opened 2021-08-31 12:34 UTC by alexal

Closes #261

2021-08-31 12:49 UTC, craicoverflow requested changes
The sub modules cannot download from `github.com/redhat-developer/app-services-sdk-go/internal` because `internal` means it is not exposed. This was not an issue previously because they were not separate.

```shell
❯ cd kafkainstance
❯ go mod tidy
go: finding module for package github.com/redhat-developer/app-services-sdk-go/internal
github.com/redhat-developer/app-services-sdk-go/kafkainstance/apiv1internal imports
	github.com/redhat-developer/app-services-sdk-go/internal: module github.com/redhat-developer/app-services-sdk-go/internal: Get "https://proxy.golang.org/github.com/redhat-developer/app-services-sdk-go/internal/@v/list": dial tcp 74.125.193.141:443: i/o timeout
```

So the solution here is to put the `api_config` file into a package called `common`.

2021-08-31 13:05 UTC, craicoverflow commented
The reason I suggested "common" was because I have seen it used in other projects ([example])(https://github.com/prometheus/client_golang/blob/master/go.mod#L9) but upon checking so is "core".

"core" makes more sense as it common as a general term for this.

2021-08-31 13:34 UTC, alexal commented
I've moved APIConfig to core. Please review.

2021-09-01 09:08 UTC, craicoverflow requested changes
Once quick change needed

2021-09-01 09:08 UTC, craicoverflow commented on core/go.mod
> +go 1.13
"core" does not need to be its own separate module - it is part of the root module. You can just remove this file and leave everything else as is.

2021-09-01 10:35 UTC, alexal commented
> Once quick change needed

Done.

2021-09-01 10:40 UTC, wtrocki approved these changes

2021-09-01 12:48 UTC, craicoverflow approved these changes

2021-09-01 12:48 UTC, merged